[cultural_events]
# datos.madrid.es cultural programming
json_url = "https://datos.madrid.es/egob/catalogo/300107-0-agenda-actividades-eventos.json"
xml_url = "https://datos.madrid.es/egob/catalogo/300107-0-agenda-actividades-eventos.xml"
csv_url = "https://datos.madrid.es/egob/catalogo/300107-0-agenda-actividades-eventos.csv"

[city_events]
# esmadrid.com tourism/city events
xml_url = "https://www.esmadrid.com/opendata/agenda_v1_es.xml"

[filter]
# Plaza de España coordinates
latitude = 40.42338
longitude = -3.71217
radius_km = 1.0  # Maximum radius for event fetching (supports distance slider UI)

# Distrito filtering
distritos = ["CENTRO", "MONCLOA-ARAVACA"]

# Time filtering
past_events_weeks = 2  # Exclude events started >2 weeks ago

[output]
html_path = "public/index.html"
json_path = "public/events.json"

[snapshot]
data_dir = "data"

[fetch]
# Respectful upstream fetching configuration
# Mode: "production" for hourly cron, "development" for frequent testing
mode = "development"

# Development mode settings (used during frequent testing):
# - Cache TTL: 1 hour (aggressive caching to avoid hitting upstream)
# - Min delay: 5 seconds between requests to same host
# - Max request rate: 1 request per 5 minutes per URL
# - Logs warnings when making real HTTP requests

# Production mode settings (used for hourly cron):
# - Cache TTL: 30 minutes (fresh data)
# - Min delay: 2 seconds between requests to same host
# - Max request rate: 1 request per hour per URL
# - Standard respectful behavior for automated systems

# HTTP cache directory (created automatically)
cache_dir = "data/http-cache"

# Request audit trail (tracks all HTTP requests with timing/cache hits)
audit_path = "data/request-audit.json"

[server]
# For development only
port = 8080
