name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.25'
          cache: true
          cache-dependency-path: generator/go.sum

      - name: Cache HTTP data
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: data/http-cache
          key: http-cache-${{ github.run_id }}
          restore-keys: |
            http-cache-

      - name: Install just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - name: Check formatting
        run: just fmt-check

      - name: Run tests
        # Tests use fixtures from testdata/ - no AEMET_API_KEY needed
        run: just test

      - name: Build FreeBSD binary
        run: just freebsd

      - name: Upload FreeBSD binary
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: buildsite-freebsd
          path: build/buildsite
          retention-days: 1

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Go
        uses: actions/setup-go@44694675825211faa026b3c33043df3e48a5fa00 # v6.0.0
        with:
          go-version: '1.25'
          cache: true
          cache-dependency-path: generator/go.sum

      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - name: Run integration tests (with HTML validation)
        run: just test-integration

  deploy:
    name: Deploy to NFSN
    runs-on: ubuntu-latest
    needs: build-and-test
    # Only deploy from the original repository, not from forks
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      github.repository == 'ericphanson/plazaespana.info'
    env:
      NFSN_HOST: ${{ secrets.NFSN_HOST }}
      NFSN_USER: ${{ secrets.NFSN_USER }}
      AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}  # Optional: for weather forecasts

    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - name: Download FreeBSD binary
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: buildsite-freebsd
          path: build/

      - name: Hash CSS
        run: just hash-css

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NFSN_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.NFSN_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to NFSN
        run: just deploy-only
