name: Fetch AWStats Archives

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: awstats-fetch
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch-archives:
    name: Fetch and archive AWStats database snapshots
    runs-on: ubuntu-latest
    # Only fetch archives from the original repository, not from forks
    if: github.repository == 'ericphanson/plaza-espana-calendar'

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0  # Full history needed for git operations

      - name: Setup SSH for NFSN
        env:
          NFSN_SSH_KEY: ${{ secrets.NFSN_SSH_KEY }}
          NFSN_HOST: ${{ secrets.NFSN_HOST }}
          NFSN_KNOWN_HOST: ${{ secrets.NFSN_KNOWN_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "$NFSN_SSH_KEY" > ~/.ssh/nfsn_awstats
          chmod 600 ~/.ssh/nfsn_awstats
          echo "$NFSN_KNOWN_HOST" >> ~/.ssh/known_hosts
          cat >> ~/.ssh/config <<EOF
          Host $NFSN_HOST
            IdentityFile ~/.ssh/nfsn_awstats
          EOF

      - name: Setup Just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Fetch statistics archives and update/create PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NFSN_HOST: ${{ secrets.NFSN_HOST }}
          NFSN_USER: ${{ secrets.NFSN_USER }}
        run: |
          just fetch-stats-archives
