name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  cleanup-preview:
    runs-on: ubuntu-latest
    # Only cleanup previews from the original repository, not from forks
    # Also skip Dependabot PRs (they never get previews)
    if: |
      github.event.pull_request.head.repo.full_name == github.repository &&
      github.event.pull_request.user.login != 'dependabot[bot]'

    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Install just
        uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.NFSN_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.NFSN_HOST }} >> ~/.ssh/known_hosts

      - name: Clean up preview
        env:
          NFSN_HOST: ${{ secrets.NFSN_HOST }}
          NFSN_USER: ${{ secrets.NFSN_USER }}
        run: |
          just preview-cleanup PR${{ github.event.pull_request.number }}

      - name: Find existing comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- preview-deployment -->'

      - name: Update PR comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        if: steps.find-comment.outputs.comment-id != ''
        with:
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: |
            <!-- preview-deployment -->
            ## 🧹 Preview Cleaned Up

            The preview deployment for this PR has been removed.

            ---
            *Cleaned up: ${{ github.event.pull_request.closed_at }}*
